### test endpoint from authController.js
GET http://localhost:5001/
Content-Type: application/json

### register
POST http://localhost:5001/register
Content-Type: application/json

{
    "firstname": "Robert",
    "lastname": "McCrary",
    "username": "Robert McCrary",
    "email": "rlmccrary1210@gmail.com",
    "password": "scottlee23"
}

### login
POST http://localhost:5001/login
Content-Type: application/json

{
    "email": "rlmccrary1210@gmail.com",
    "password": "scottlee23"
}


### Get User Profile
GET http://localhost:5001/profile
