### register
POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
    "username": "Robert_McCrary",
    "email": "rlmccrary1210@gmail.com",
    "password": "scottlee23"
}
 
### login
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "email": "rlmccrary1210@gmail.com",
    "password": "scottlee23",
}